"""Author: Mark Hanegraaff -- 2020

This module contains a collection of calculations shared by the trading
strategies contained in this package.
"""
import pandas as pd
from datetime import datetime
from connectors import intrinio_data
from exception.exceptions import ValidationError, CalculationError, DataError


def mark_to_market(data_frame: object, price_date: datetime):
    """
        Peforms a Mark to Market on a Pandas dataframe representing
        a ranked portfolio, and given a price date. This is used
        to calculate returns on a portfolio generated by one of the
        strategies

        The dataframe must contain the following columuns:

        * ticker
        * analysis_price

        and will add:

        * current_price
        * actual_return

        Parmeters
        ---------
        data_frame : Pandas DataFrame
            portfolio dataframe
        price_date : datetime
            price date, current or historical

        Returns
        ---------
        A new dataframe with the added columns

        Raises
        ---------
        ValidationError if parameters are incorrect
        DataError if there are problems reading price data
    """

    if (data_frame is None or price_date is None):
        raise ValidationError(
            "Invalid Parameters supplied to Mark to Market calculation", None)

    if ('ticker' not in data_frame.columns
            or 'analysis_price' not in data_frame.columns):
        raise ValidationError(
            "Could not extract required fields for Mark to Market calculation", None)

    mmt_prices = []

    for ticker in data_frame['ticker']:
        try:
            latest_price = intrinio_data.get_latest_close_price(ticker, price_date, 5)[
                1]
            mmt_prices.append(latest_price)
        except Exception as e:
            raise DataError("Could not perform MMT calculation", e)

    data_frame['current_price'] = mmt_prices
    data_frame['actual_return'] = (data_frame['current_price'] -
                                   data_frame['analysis_price']) / data_frame['analysis_price']
    return data_frame
